name: CI

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  commits:
    name: commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.1.0

  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings

      - name: Format
        run: cargo fmt --all -- --check

  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: linter

    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: cargo build --release
  
      - name: Run tests
        run: cargo test